
recaptcha_public_key: 
recaptcha_private_key: 
exception_notification_email:
donate_code: ''
enable_screenshots: 'false'
pagekeeper_link_code: ''
# Include port in app_domain if developing on localhost, e.g. "localhost:3000"
app_domain: ''

production:
  recaptcha_public_key: 
  recaptcha_private_key: 
  exception_notification_email:
  app_domain: ''
